---
name: Run CI Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

env:
  TEST_DB_HOST: 127.0.0.1
  TEST_DB_PORT: 3306
  TEST_DB_USER: root
  TEST_DB_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}
  TEST_DB_DATABASE: testr2

jobs:
  fetch-s2-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Get supported versions of Singlestore
        id: get_versions
        uses: singlestore-labs/singlestore-supported-versions@main

  test:
    needs: fetch-s2-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        singlestore_version: ${{ fromJson(needs.fetch-s2-versions.outputs.versions) }}
        java: ["8", "11", "17"]

    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        ports:
          - "3306:3306"
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}
          SINGELSTORE_VERSION: ${{ matrix.singlestore_version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java || '21' }}
          cache: maven
          distribution: 'adopt'

      - name: Run Tests
        run: mvn clean test ${{ matrix.java == '8' && '-P java8' || '' }}
